name: RabbitMQ
driverClass: io.openmessaging.benchmark.driver.rabbitmq.RabbitMqBenchmarkDriver
producerCreationDelay: 100
producerCreationBatchSize: 5
consumerCreationDelay: 100
consumerCreationBatchSize: 5
amqpUris:
  - amqp://omb:omb@localhost:5672
messagePersistence: false
queueType: CLASSIC
