name: Pulsar
driverClass: io.openmessaging.benchmark.driver.pulsar.PulsarBenchmarkDriver
client:
  serviceUrl: pulsar://localhost:6650
  httpUrl: http://localhost:8080
  ioThreads: 8
  connectionsPerBroker: 8
  clusterName: standalone
  namespacePrefix: public/default
  topicType: persistent
  persistence:
    ensembleSize: 1
    writeQuorum: 1
    ackQuorum: 1
    deduplicationEnabled: false
producer:
  batchingEnabled: true
  batchingMaxPublishDelayMs: 1
  batchingMaxBytes: 131072
  blockIfQueueFull: true
  pendingQueueSize: 0
consumer:
  receiverQueueSize: 10000
  subscriptionType: Failover
